env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs24.5
    - EMACS=emacs-snapshot

matrix:
  allow_failures:
    - env: EMACS=emacs-snapshot
    - env: EMACS=emacs24

before_install:
  - git submodule --quiet update --init --recursive

install:
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot &&
        sudo apt-get -qq install emacs-snapshot-el;
    fi
  - if [ "$EMACS" = 'emacs24.5' ]; then
        wget ftp://www.mirrorservice.org/sites/ftp.gnu.org/gnu/emacs/emacs-24.5.tar.gz &&
        tar -xvf emacs-24.5 &&
        cd emacs-24.5 &&
        ./configure &&
        make &&
        make install;
    fi


script:
  - emacs -batch -l ert -L . -L tests/ -l tests/duckpan-tests.el -f ert-run-tests-batch-and-exit

notifications:
  email: false
